### ISSUE TITLE
Fix this (vso upload)

### ISSUE THREAD

**Issue by ljcollins25** [Ref12/Codex#136]
```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Codex.ElasticSearch.Store.StoredBoundSourceFile.AfterDeserialization() in D:\Code\CodexRef12\src\Codex.ElasticSearch\Store\Directory\StoredBoundSourceFile.cs:line 112
   at Codex.ElasticSearch.Store.DirectoryCodexStore.FromStoredBoundFile(StoredBoundSourceFile storedBoundFile) in D:\Code\CodexRef12\src\Codex.ElasticSearch\Store\Directory\DirectoryCodexStore.cs:line 223
   at Codex.ElasticSearch.Store.DirectoryCodexStore.StoredEntityKind.<>c.<.cctor>b__13_1(StoredBoundSourceFile entity, ICodexRepositoryStore repositoryStore, DirectoryCodexStore directoryStore) in D:\Code\CodexRef12\src\Codex.ElasticSearch\Store\Directory\DirectoryCodexStore.cs:line 294
   at Codex.ElasticSearch.Store.DirectoryCodexStore.StoredEntityKind`1.Add(DirectoryCodexStore store, FileSystem fileSystem, String fullPath, ICodexRepositoryStore repositoryStore) in D:\Code\CodexRef12\src\Codex.ElasticSearch\Store\Directory\DirectoryCodexStore.cs:line 347
   at Codex.ElasticSearch.Store.DirectoryCodexStore.<>c__DisplayClass18_3.<<ReadAsync>b__1>d.MoveNext() in D:\Code\CodexRef12\src\Codex.ElasticSearch\Store\Directory\DirectoryCodexStore.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Codex.ElasticSearch.Store.DirectoryCodexStore.<>c__DisplayClass18_1.<<ReadAsync>b__2>d.MoveNext() in D:\Code\CodexRef12\src\Codex.ElasticSearch\Store\Directory\DirectoryCodexStore.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Codex.ElasticSearch.Store.DirectoryCodexStore.<ReadAsync>d__18.MoveNext() in D:\Code\CodexRef12\src\Codex.ElasticSearch\Store\Directory\DirectoryCodexStore.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Codex.Application.CodexApplication.<LoadCoreAsync>d__46.MoveNext() in D:\Code\CodexRef12\src\Codex\CodexApplication.cs:line 574
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Codex.Application.CodexApplication.LoadCore(Logger logger, String loadDirectory, Boolean clearIndicesBeforeUse, Boolean finalizeRepository, String targetIndexName) in D:\Code\CodexRef12\src\Codex\CodexApplication.cs:line 541
   at Codex.Application.CodexApplication.Load(String targetIndexName, Boolean finalize) in D:\Code\CodexRef12\src\Codex\CodexApplication.cs:line 510
   at Codex.Application.CodexApplication.Ingest(String name, String elasticsearchUrl, String ingestionDirectory, Boolean finalize, Boolean useNewBackend) in D:\Code\CodexRef12\src\Codex\CodexApplication.cs:line 490
   at Codex.Ingester.Program.<RunAsync>d__2.MoveNext() in D:\Code\CodexRef12\src\Codex.Ingester\Program.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Codex.Ingester.Program.RunOptionsAndReturnExitCode(Options options) in D:\Code\CodexRef12\src\Codex.Ingester\Program.cs:line 150
   at Codex.Ingester.Program.<>c.<Main>b__1_1(Options opts) in D:\Code\CodexRef12\src\Codex.Ingester\Program.cs:line 58
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Codex.Ingester.Program.Main(String[] args) in D:\Code\CodexRef12\src\Codex.Ingester\Program.cs:line 52
Press any key to continue . . .
```

**Comment by KirillOsenkov** [comment]
I added a workaround so that this crash doesn't tear down the entire process:
https://github.com/Ref12/Codex/commit/2ee8f461db2e1129040a2d5f19ab84a923e5ff28

**Comment by KirillOsenkov** [comment]
Some file in VSO has a reference that is outside the lines array, we should debug at some point, but at least now it shouldn't crash.

**Comment by ljcollins25** [comment]
The string split algorithm has a bug where `\r\r` is not properly split into two lines.

**Comment by ljcollins25** [comment]
`Gallery\\WebPlatform\\L2.WebUI\\L2.Tests\\Market\\Market.Gallery.WebPlatform.L2.Tests.csproj`
