### ISSUE TITLE
Add a try/catch around this stack

### ISSUE THREAD

**Issue by KirillOsenkov** [Ref12/Codex#209]
A failure to parse a single project shouldn't bring down the whole analysis:

```
2022-01-06T22:31:34.9381573Z 1/6/2022 10:31:34 PM: First chance exception: System.ArgumentException: Specified sequence has duplicate items
2022-01-06T22:31:34.9382041Z Parameter name: metadataReferences[5]
2022-01-06T22:31:34.9382461Z    at Microsoft.CodeAnalysis.PublicContract.ThrowArgumentItemNullOrDuplicateException[T](IEnumerable`1 sequence, String argumentName)
2022-01-06T22:31:34.9383332Z    at Microsoft.CodeAnalysis.ProjectInfo.Create(ProjectId id, VersionStamp version, String name, String assemblyName, String language, String filePath, String outputFilePath, CompilationOptions compilationOptions, ParseOptions parseOptions, IEnumerable`1 documents, IEnumerable`1 projectReferences, IEnumerable`1 metadataReferences, IEnumerable`1 analyzerReferences, IEnumerable`1 additionalDocuments, Boolean isSubmission, Type hostObjectType, String outputRefFilePath)
2022-01-06T22:31:34.9384317Z    at Microsoft.CodeAnalysis.CommandLineProject.CreateProjectInfo(String projectName, String language, IEnumerable`1 commandLineArgs, String projectDirectory, Workspace workspace)
2022-01-06T22:31:34.9385179Z    at Codex.Analysis.Projects.InvocationSolutionInfoBuilderBase.GetCommandLineProject(String projectPath, String projectName, String languageName, String[] args) in D:\a\1\s\src\Codex.Analysis.Managed\Projects\InvocationSolutionInfoBuilderBase.cs:line 87
2022-01-06T22:31:34.9386088Z    at Codex.Analysis.Projects.InvocationSolutionInfoBuilderBase.StartLoadProject(CompilerInvocation invocation) in D:\a\1\s\src\Codex.Analysis.Managed\Projects\InvocationSolutionInfoBuilderBase.cs:line 48
2022-01-06T22:31:34.9386818Z    at Codex.Analysis.Projects.BinLogProjectAnalyzer.SolutionInfoBuilder.Initialize() in D:\a\1\s\src\Codex.Analysis.Managed\Projects\BinLogProjectAnalyzer.cs:line 118
2022-01-06T22:31:34.9387577Z    at Codex.Analysis.Projects.BinLogProjectAnalyzer.SolutionInfoBuilder..ctor(String binLogFilePath, Repo repo) in D:\a\1\s\src\Codex.Analysis.Managed\Projects\BinLogProjectAnalyzer.cs:line 101
2022-01-06T22:31:34.9389578Z    at Codex.Analysis.Projects.BinLogProjectAnalyzer.CreateProjects(Repo repo) in D:\a\1\s\src\Codex.Analysis.Managed\Projects\BinLogProjectAnalyzer.cs:line 51
2022-01-06T22:31:34.9390258Z    at Codex.Import.RepositoryImporter.<Import>d__6.MoveNext() in D:\a\1\s\src\Codex.Analysis\Import\RepositoryImporter.cs:line 59
```

**Comment by KirillOsenkov** [comment]
https://github.com/Ref12/Codex/blob/ccd552ae163703e108cf460ccae2d4a203ed9bc0/src/Codex.Analysis.Managed/Projects/InvocationSolutionInfoBuilderBase.cs#L53
